# Generated by Django 3.2.25 on 2024-10-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStatistics_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.CharField(max_length=20)),
                ('chart_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('insurance_classification', models.CharField(max_length=50)),
                ('income_aggregation', models.CharField(max_length=50)),
                ('treating_doctor', models.CharField(max_length=50)),
                ('assist', models.CharField(max_length=50)),
                ('same_day_reception', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=50)),
                ('total_medical_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('out_of_pocket_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('non_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_storage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_receipt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_online', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prefectural_issued_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disapproval_for_healthy_lifestyle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unexpected_player', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_number_of_outstanding_players', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('classification_of_medical_expenses', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('first_visit', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_path', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_propensity', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_classification_2', models.CharField(blank=True, max_length=50, null=True)),
                ('recall_classification', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'medical_statistics_2',
                'managed': True,
                'unique_together': {('treatment_date', 'chart_number')},
            },
        ),
    ]
