# Generated by Django 3.2.25 on 2024-10-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medicalstatistics_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalStatistics',
        ),
        migrations.DeleteModel(
            name='MedicalStatistics_1',
        ),
    ]
