name: Django CI

on:
  push:
    branches:
      - master
  
  
jobs:
  test:
    runs-on: ubuntu-latest    

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Install docker
      uses: docker/setup-buildx-action@v3

    - name: Generate django secret key
      run:
        echo "DEBUG: ${{ secrets.DJANGO_PROJECT_KEY }}"
        echo "${{ secrets.DJANGO_PROJECT_KEY }}" > django_project_key.json
        cat django_project_key.json


    - name: Build the Docker image
      run: docker build . -t oksusu2020/django_project:$(date +%Y%m%d)

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}      

    - name: Push the Docker image
      run: docker push oksusu2020/django_project:$(date +%Y%m%d)

    

    